let departamento = prompt("ingrese el departamento").toLocaleLowerCase();

const depar = [
    "amazonas",
    "antioquia",
    "arauca",
    "atlantico",
    "bolivar",
    "boyaca",
    "caldas",
    "caqueta",
    "casanare",
    "cauca",
    "cesar ",
    "choco",
    "cordoba",
    "cundinamarca",
    "guania",
    "guaviare",
    "huila",
    "guajira",
    "magdalena",
    "meta",
    "nariño",
    "norte de santander",
    "putumayo ",
    "quindio",
    "risaralda",
    "san andres",
    "santander",
    "sucre",
    "tolima",
    "valle del cauca",
    "vaupes",
    "vichada",

    "leticia",
    "medellin",
    "arauca ",
    "barranquilla",
    "cartagena",
    "tunja ",
    "manizales",
    "florencia",
    "yopal",
    "popayan",
    "valledupar",
    "quibdo",
    "monteria",
    "bogota",
    "inirida",
    "guaviare",
    "neiva",
    "riohacha",
    "santa marta",
    "villavicencio",
    "pasto",
    "cucuta",
    "mocoa",
    "armenia",
    "pereira",
    "san andres",
    "bucaramanga",
    "sincelejo",
    "ibague",
    "cali",
    "mitu",
    "puerto carreño",
];
for (let i = 0; i < depar.length; i++) {
    if (depar[i] == departamento) {
        alert("la capital de " + departamento +" es "+depar[i+32]);
    }
}


